// Canonical table name constants — import these instead of hard-coding strings.
// These match the SQLite table names and the Supabase table names exactly.
export const TABLE = {
  PROFILES: 'profiles',
  CONFIGURATIONS: 'configurations',
  BUSINESS_ROLES: 'business_roles',
  TEAM_MEMBERS: 'team_members',
  MATERIAL_MASTER: 'material_master',
  INVENTORY: 'inventory',
  SUPPLIER_PRODUCT_MAP: 'supplier_product_map',
  SUPPLIERS: 'suppliers',
  CUSTOMERS: 'customers',
  SALES_BILL: 'sales_bill',
  PURCHASES: 'purchases',
  PURCHASE_ORDERS: 'purchase_orders',
  DELIVERY_CHALLANS: 'delivery_challans',
  SALES_CHALLANS: 'sales_challans',
  SALES_RETURNS: 'sales_returns',
  PURCHASE_RETURNS: 'purchase_returns',
  PHYSICAL_INVENTORY: 'physical_inventory',
  DOCTOR_MASTER: 'doctor_master',
  EWAYBILLS: 'ewaybills',
  PROMOTIONS: 'promotions',
  MRP_CHANGE_LOG: 'mrp_change_log',
  CUSTOMER_PRICE_LIST: 'customer_price_list',
  MATERIAL_PRICE_LIST: 'material_price_list',
  MBC_CARDS: 'mbc_cards',
  GL_MASTER: 'gl_master',
  GL_ASSIGNMENTS: 'gl_assignments',
  COMPANY_CODES: 'company_codes',
  SET_OF_BOOKS: 'set_of_books',
  CATEGORIES: 'categories',
  SUB_CATEGORIES: 'sub_categories',
  DISTRIBUTORS: 'distributors',
  JOURNAL_ENTRY_HEADER: 'journal_entry_header',
  JOURNAL_ENTRY_LINES: 'journal_entry_lines',
  MBC_CARD_TYPES: 'mbc_card_types',
  MBC_CARD_TEMPLATES: 'mbc_card_templates',
  MBC_CARD_HISTORY: 'mbc_card_history',
  MBC_CARD_VALUE_HISTORY: 'mbc_card_value_history',

  // Internal sync tables — never pushed to Supabase
  SYNC_QUEUE: '_sync_queue',
  SYNC_META: '_sync_meta',
  LOCAL_AUTH: '_local_auth',
  MIGRATIONS: '_migrations',
  INITIAL_SYNC_STATE: '_initial_sync_state',
} as const;

export type TableName = (typeof TABLE)[keyof typeof TABLE];

// Tables that are synced to Supabase (excludes internal _ tables)
export const SYNCABLE_TABLES: TableName[] = [
  TABLE.PROFILES,
  TABLE.CONFIGURATIONS,
  TABLE.BUSINESS_ROLES,
  TABLE.TEAM_MEMBERS,
  TABLE.MATERIAL_MASTER,
  TABLE.INVENTORY,
  TABLE.SUPPLIER_PRODUCT_MAP,
  TABLE.SUPPLIERS,
  TABLE.CUSTOMERS,
  TABLE.SALES_BILL,
  TABLE.PURCHASES,
  TABLE.PURCHASE_ORDERS,
  TABLE.DELIVERY_CHALLANS,
  TABLE.SALES_CHALLANS,
  TABLE.SALES_RETURNS,
  TABLE.PURCHASE_RETURNS,
  TABLE.PHYSICAL_INVENTORY,
  TABLE.DOCTOR_MASTER,
  TABLE.EWAYBILLS,
  TABLE.PROMOTIONS,
  TABLE.MRP_CHANGE_LOG,
  TABLE.CUSTOMER_PRICE_LIST,
  TABLE.MATERIAL_PRICE_LIST,
  TABLE.MBC_CARDS,
  TABLE.GL_MASTER,
  TABLE.GL_ASSIGNMENTS,
  TABLE.COMPANY_CODES,
  TABLE.SET_OF_BOOKS,
  TABLE.CATEGORIES,
  TABLE.SUB_CATEGORIES,
  TABLE.DISTRIBUTORS,
  TABLE.JOURNAL_ENTRY_HEADER,
  TABLE.JOURNAL_ENTRY_LINES,
  TABLE.MBC_CARD_TYPES,
  TABLE.MBC_CARD_TEMPLATES,
  TABLE.MBC_CARD_HISTORY,
  TABLE.MBC_CARD_VALUE_HISTORY,
];
